# Generated by Django 4.1.7 on 2023-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_owner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='hook_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Hook id'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='hook_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Hook id'),
        ),
    ]
