# Generated by Django 4.1.7 on 2023-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_basket_hook_id_basketitem_hook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='hook_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Hook'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='hook_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Hook id'),
        ),
    ]
