# Generated by Django 4.1.7 on 2023-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_basket_hook_id_alter_basketitem_hook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='hook_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Hook'),
        ),
    ]
