# Generated by Django 4.1.7 on 2023-03-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanbasket', '0004_basket_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='identifier',
            new_name='hook_id',
        ),
    ]
